### ISSUE TITLE
Not Sure Where To Hand Things In

### ISSUE THREAD

**Issue by ryanpurdyca** [ryanpurdyca/glacier-app#1]
@ericadamski can't find instructions on canvas nor assignment (https://github.com/ericadamski/simple-chat-app/wiki/Week-1#exercises) on how to hand stuff in 😭

Also (my bad) I accidentally originally created this issue on the wrong page so you may see that to 👀

**Comment by ericadamski** [comment]
Thats fine, we'll just be handing in things over github, so you can create an issue with the title called marks week 1 and tag heather, sam and me. Let me know if you have any more questions

**Comment by ericadamski** [comment]
Thanks, its just you Sam, and Heather correct?

**Comment by ryanpurdyca** [comment]
@ericadamski correct, just us 3 :)
