### ISSUE TITLE
Post Deliverable Checklist

### ISSUE THREAD

**Issue by ryanpurdyca** [ryanpurdyca/glacier-app#12]
Yo @ericadamski ✌🏻

Progress:
Paper wireframes & colour scheme

Next steps:
Begin coding

Issues from last week:
MUI Forms

# Positives 

+ Lead the creation of our moodboard and collected pieces of work from everyone
+ Direction. We all align with our ideas fairly quickly
+ Nobody skipping classes

# Improvements

+ Need to use Slack more
+ Need to push for more focus on code and ui and spend less time on brand, and other elements that are not project related

# Feedback

- What is a good way to push the team to use Slack more?

**Comment by ericadamski** [comment]
That is a good question, not sure what the answer to that one is Ryan.
