### ISSUE TITLE
Pre-deliverables

### ISSUE THREAD

**Issue by ericadamski** [ryanpurdyca/glacier-app#13]
Complete the pre-deliverables for deliverable 2 https://github.com/ericadamski/simple-chat-app/wiki/Pre-Deliverable-Checklist. You can have until sunday

**Comment by ericadamski** [comment]
@HeatherAnn @RyanNickPurdy @samzah

**Comment by samzah** [comment]
@ericadamski 
Heather created the new milestone, and created sprint 2. We put some issues as well. I'm not sure what else we need to do I feel like we are missing something. Please help.
